version: '3.8'

services:
    db:
       
        
        
        image:  postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        container_name: postgres_db

        


        
    web:
        tty: true
        
        command: python3 manage.py runserver 0.0.0.0:8000
        build:  .
        volumes:
            - .:/usr/src/app
        ports:
            -   8000:8000
        container_name: django_container
        
        
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_HOST: db
        depends_on:
            - db
            
